@extends('layout')
{{-- Copilot autogenerated code --}}
@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Prijavi se') }}</div>

                    <div class="card-body">
                        <x-form
                        :existingData="$existingData"
                        submitRouteName="login"
                        backRouteName="home"
                        submitButtonName="Prijavi se"
                        backButtonName="Domov">

                            <x-input
                            type="text"
                            name="username"
                            displayedName="Uporabniško ime" />

                            <x-input
                            type="password"
                            name="password"
                            displayedName="Geslo" />

                        </x-form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
